/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/dashboard/index.html', './src/dashboard/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#30353a',
        secondary: '#d0bcff',
        'on-tertiary': '#233143',
        'electric-blue': '#0ea5e9',
        'soft-violet': '#a78bfa',
        'inverse-on-surface': '#2c3135',
        'on-background': '#dee3e9',
        'surface-bright': '#353a3e',
        'on-error-container': '#ffdad6',
        tertiary: '#b9c8de',
        'on-primary-fixed': '#001e2f',
        'surface-tint': '#89ceff',
        'surface-container': '#1b2024',
        'surface-elevated': '#0d1e33',
        'surface-dim': '#0f1418',
        'on-surface-variant': '#bec8d2',
        error: '#ffb4ab',
        'primary-fixed-dim': '#89ceff',
        'on-secondary-fixed-variant': '#5516be',
        'surface-container-high': '#252b2f',
        'on-error': '#690005',
        'on-secondary': '#3c0091',
        'on-primary-container': '#003751',
        'glow-blue': 'rgba(14, 165, 233, 0.15)',
        'on-tertiary-fixed-variant': '#3a485a',
        primary: '#89ceff',
        'secondary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#b9c8de',
        'secondary-fixed-dim': '#d0bcff',
        'surface-container-lowest': '#0a0f13',
        'on-primary': '#00344d',
        'surface-container-low': '#171c20',
        'primary-fixed': '#c9e6ff',
        'sapphire-deep': '#051424',
        'tertiary-container': '#8e9db2',
        'on-secondary-container': '#c4abff',
        'primary-container': '#0ea5e9',
        background: '#0f1418',
        surface: '#0f1418',
        outline: '#88929b',
        'on-primary-fixed-variant': '#004c6e',
        'on-surface': '#dee3e9',
        'on-tertiary-fixed': '#0e1c2d',
        'on-tertiary-container': '#263446',
        'surface-variant': '#30353a',
        'tertiary-fixed': '#d5e4fa',
        'on-secondary-fixed': '#23005c',
        'error-container': '#93000a',
        'secondary-container': '#571bc1',
        'inverse-surface': '#dee3e9',
        'outline-variant': '#3e4850',
        'inverse-primary': '#006591',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '2rem',
        xs: '0.5rem',
        sm: '1rem',
        gutter: '2rem',
        xl: '8rem',
        lg: '4rem',
        margin: '2.5rem',
        unit: '4px',
      },
      fontFamily: {
        'headline-md': ['Geist'],
        'headline-lg-mobile': ['Geist'],
        display: ['Geist'],
        'body-md': ['Geist'],
        'label-sm': ['JetBrains Mono'],
        'headline-lg': ['Geist'],
        'body-lg': ['Geist'],
        'code-md': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '1.7', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
