/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/dashboard/index.html', './src/dashboard/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // "Ultra Engineering Terminal" (stitch_design_enhancement_engine/code.html) — the token
        // *names* below are unchanged from the original Electric Sapphire scaffold so every
        // component that references them re-themes automatically; only the hex values moved to
        // the new near-black/neon palette. neon-cyan/neon-pink/neon-green are the new accents
        // named honestly, for new code — electric-blue/soft-violet are kept as aliases pointing
        // at the same two colors so the ~15 files already using those classes don't need editing.
        'neon-cyan': '#00f0ff',
        'neon-pink': '#f8acff',
        'neon-green': '#33fb0a',
        'surface-container-highest': '#353535',
        secondary: '#c0c1ff',
        'on-tertiary': '#2f3131',
        'electric-blue': '#00f0ff',
        'soft-violet': '#f8acff',
        'inverse-on-surface': '#303030',
        'on-background': '#e5e2e1',
        'surface-bright': '#393939',
        'on-error-container': '#ffdad6',
        tertiary: '#c6c6c7',
        'on-primary-fixed': '#1c1b1b',
        'surface-tint': '#c8c6c5',
        'surface-container': '#202020',
        'surface-elevated': '#242424',
        'surface-dim': '#131313',
        'on-surface-variant': '#c4c7c7',
        error: '#ffb4ab',
        'primary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed-variant': '#2f2ebe',
        'surface-container-high': '#2a2a2a',
        'on-error': '#690005',
        'on-secondary': '#1000a9',
        'on-primary-container': '#7e7d7d',
        'glow-blue': 'rgba(0, 240, 255, 0.08)',
        'on-tertiary-fixed-variant': '#454747',
        primary: '#c8c6c5',
        'secondary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#c6c6c7',
        'secondary-fixed-dim': '#c0c1ff',
        'surface-container-lowest': '#0e0e0e',
        'on-primary': '#313030',
        'surface-container-low': '#1b1b1c',
        'primary-fixed': '#e5e2e1',
        'sapphire-deep': '#0a0a0a',
        'tertiary-container': '#101213',
        'on-secondary-container': '#b0b2ff',
        'primary-container': '#121212',
        background: '#131313',
        surface: '#131313',
        outline: '#8e9192',
        'on-primary-fixed-variant': '#474646',
        'on-surface': '#e5e2e1',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-container': '#7c7d7e',
        'surface-variant': '#353535',
        'tertiary-fixed': '#e2e2e2',
        'on-secondary-fixed': '#07006c',
        'error-container': '#93000a',
        'secondary-container': '#3131c0',
        'inverse-surface': '#e5e2e1',
        'outline-variant': '#444748',
        'inverse-primary': '#5f5e5e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        md: '2rem',
        xs: '0.5rem',
        sm: '1rem',
        gutter: '2rem',
        xl: '8rem',
        lg: '4rem',
        margin: '2.5rem',
        unit: '4px',
      },
      fontFamily: {
        'headline-md': ['Geist'],
        'headline-lg-mobile': ['Geist'],
        display: ['Geist'],
        'body-md': ['Geist'],
        'label-sm': ['Geist Mono'],
        'headline-lg': ['Geist'],
        'body-lg': ['Geist'],
        'code-md': ['Geist Mono'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '1.7', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
